import assert from 'node:assert/strict';
import {createRequire} from 'node:module';
const {chromium} = createRequire(import.meta.url)('playwright');
const browser = await chromium.launch({headless:true});
const base = process.env.QUOTE_BASE_URL || 'http://127.0.0.1:8773/';
const page = await browser.newPage({viewport:{width:390,height:844}});
// No analytics traffic and no external messages, even when testing the published page.
await page.route('**/*', route => {
  const url = route.request().url();
  if (url.startsWith(base) || url.startsWith('blob:') || url.startsWith('data:')) return route.continue();
  return route.abort();
});
await page.addInitScript(() => { window.__opened=[]; window.open=(url)=>{window.__opened.push(url);return null;}; });
await page.goto(base+'?utm_source=google&utm_campaign=24177873330&gclid=QA_ONLY_NOT_REAL',{waitUntil:'networkidle'});
await page.locator('a[href="#store-quote"]').first().click();
await page.locator('#store-quote').waitFor({state:'visible'});
assert.equal(await page.locator('input[name="measurement"]').isChecked(),false);
await page.locator('.quote-submit').click();
assert.equal(await page.evaluate(()=>window.__opened.length),0,'Invalid form must not open WhatsApp');
await page.locator('input[name="name"]').fill('عميل اختبار');
await page.locator('input[name="activity"]').fill('متجر عطور');
await page.locator('select[name="need"]').selectOption({label:'إنشاء متجر جديد'});
await page.locator('select[name="budget"]').selectOption({label:'٢٬٠٠٠–٣٬٤٩٩ ريال'});
await page.locator('select[name="timing"]').selectOption({label:'خلال شهر'});
await page.locator('.quote-submit').click();
const first=new URL(await page.evaluate(()=>window.__opened[0])).searchParams.get('text');
assert.match(first,/measurement_consent:denied/);
assert.doesNotMatch(first,/gclid:/);
assert.match(first,/ref:google:24177873330/);
assert.match(first,/متجر عطور/);
await page.locator('input[name="measurement"]').check();
await page.locator('.quote-submit').click();
const second=new URL(await page.evaluate(()=>window.__opened[1])).searchParams.get('text');
assert.match(second,/gclid:QA_ONLY_NOT_REAL/);
assert.match(second,/measurement_consent:granted/);
assert.equal(first.match(/MW-[a-f0-9-]+/)[0],second.match(/MW-[a-f0-9-]+/)[0],'Repeated opens retain the same request reference');
const events=await page.evaluate(()=>window.dataLayer.map(x=>Array.from(x)));
assert.doesNotMatch(JSON.stringify(events),/عميل اختبار|متجر عطور|QA_ONLY_NOT_REAL|qualified_lead|generate_lead|purchase/);
assert.ok(events.some(x=>x[1]==='quote_whatsapp_open'));
assert.ok(await page.locator('a[href*="mohtaway.com/"]').count(),'Purchase paths retained');
assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);
if(process.env.QUOTE_SCREENSHOT) await page.screenshot({path:process.env.QUOTE_SCREENSHOT});
await page.keyboard.press('Escape');
assert.equal(await page.locator('#store-quote').isVisible(),false);
await page.setViewportSize({width:1440,height:1000});
await page.locator('a[href="#store-quote"]').first().click();
assert.equal(await page.locator('#store-quote').isVisible(),true);
await browser.close();
console.log('PASS: validation, optional consent, attribution handoff, dedup reference, no PII in analytics, no fake lead/purchase, mobile and desktop dialog. External traffic blocked.');
